/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\window-railing.glb 
*/

import React, { type JSX, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

type WindowProps = JSX.IntrinsicElements["group"];

export const Window: React.FC<WindowProps> = (props) => {
	const { nodes, materials } = useGLTF(
		"models/window-railing.glb"
	) as unknown as {
		nodes: {
			Object_16: THREE.Mesh;
			Object_17: THREE.Mesh;
			Object_18: THREE.Mesh;
			Object_11: THREE.Mesh;
			Object_12: THREE.Mesh;
			Object_13: THREE.Mesh;
			Object_8: THREE.Mesh;
			Object_9: THREE.Mesh;
			Cube: THREE.Mesh;
			Object_4: THREE.Mesh;
		};
		materials: {
			Glass: THREE.Material;
			Material: THREE.Material;
			["Test Glass"]: THREE.Material;
			Material_35: THREE.Material;
		};
	};

	// Create transparent glass material once
	const glassMaterial = useMemo(
		() =>
			new THREE.MeshPhysicalMaterial({
				color: 0xffffff,
				metalness: 0,
				roughness: 0,
				transmission: 1, // makes it glass-like
				opacity: 0.3, // adjust transparency
				transparent: true,
				ior: 1.5,
				thickness: 0.1,
			}),
		[]
	);

	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group position={[0, 0.909, 40.492]}>
					<group position={[-33.862, -0.909, -40.492]}>
						{/* Transparent Glass */}
						<mesh
							geometry={nodes.Object_16.geometry}
							material={glassMaterial}
						/>
						<mesh
							geometry={nodes.Object_17.geometry}
							material={materials.Material}
						/>
						<mesh
							geometry={nodes.Object_18.geometry}
							material={materials.Material}
						/>
					</group>
				</group>
				<group position={[-21.038, 0.023, 38.465]}>
					<group position={[21.038, -0.023, -38.465]}>
						{/* Transparent Glass */}
						<mesh
							geometry={nodes.Object_11.geometry}
							material={glassMaterial}
						/>
						<mesh
							geometry={nodes.Object_12.geometry}
							material={materials.Material}
						/>
						<mesh
							geometry={nodes.Object_13.geometry}
							material={materials.Material}
						/>
					</group>
					<group position={[21.038, 0.804, -0.306]}>
						<group position={[0, -0.826, -38.158]}>
							<mesh
								geometry={nodes.Object_8.geometry}
								material={materials.Material}
							/>
							<mesh
								geometry={nodes.Object_9.geometry}
								material={materials.Material}
							/>
						</group>
					</group>
				</group>
			</group>
			<mesh geometry={nodes.Cube.geometry} material={materials.Material} />
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials.Material_35}
				position={[-100.525, -292.339, 3.874]}
			/>
		</group>
	);
};

useGLTF.preload("models/window-railing.glb");
